# Name of output folder
sample_name: "ARZ561_170c7ea3_err=3_minR=5_maxR=80"

# Input FASTQ files. Can be a (zipped) FASTQ file or a folder containing (zipped) FASTQ files
input_fastq: "/beegfs-storage/projects/wp4/nobackup/workspace/camille_test/ampliconthemato/data/2777435/ARZ561_170c7ea3.fastq"

# Reference genome
reference_fasta: "/data/ref_genomes/GRCh38/GCA_000001405.15/GCA_000001405.15_GRCh38_no_alt_analysis_set_masked.fasta"

# BED file containing intervals with regions that are going to be analysed
targets_bed: "/beegfs-storage/projects/wp4/nobackup/workspace/camille_test/ampliconthemato/data/primer_data/FLT3_3kb.bed"


############################
######### Optional #########
############################
#
# Max differences between UMI in read and UMI pattern
umi_errors: 3

# Min number of reads required for a consensus read
min_reads_per_cluster: 5

# Max number of 1D used for a consensus read
max_reads_per_cluster: 80

# Min overlap with target region
min_overlap: 0.90

# Balance forward and reverse 1D reads in clusters
balance_strands: True

# Medaka model used to compute consensus reads (default = "r1041_e82_400bps_sup_v4.3.0")
medaka_model: "r1041_e82_400bps_sup_v4.3.0"

# Forward tail of primer (Ftail...UMI...primer)
fwd_context: "GTATCGTGTAGAGACTGCGTAGG"

# Reverse tail of primer (Rtail...UMI...primer)
rev_context: "AGTGATCGAGTCAGTGCGAGTG"

# Forward UMI (Ftail...UMI...primer) The inside sequence can be appended to the UMI sequence to increase specificity, e.g. UMI then 4bases of primer: TTTVVVVTTVVVVTTVVVVTTVVVVTTTaggt
fwd_umi: "TTTVVVVTTVVVVTTVVVVTTVVVVTTT"

# Reverse UMI (Rtail...UMI...primer) The inside sequence can be appended to the UMI sequence to increase specificity, e.g. UMI then 4bases of primer: TTTVVVVTTVVVVTTVVVVTTVVVVTTTaggt
rev_umi: "AAABBBBAABBBBAABBBBAABBBBAAA"

# Minimum combined UMI length
min_length: 40

# Maximum combined UMI length
max_length: 75

# should the fastq reads be length and quality filtered?
filter_reads: True

# fastq min read length (if filter_reads is set to true)
min_read_len: 2000

# fastq min read length (if filter_reads is set to true)
max_read_len: 4000

# fastq min mean read quality score (if filter_reads is set to true)
min_mean_qual: 70

# Variant filtering options for varscan
varscan_params: '--variants 1 --output-vcf 1 --min-coverage 8 --min-avg-qual 0 --min-var-freq 0.01 --strand-filter 0 --p-value 1 --min-reads2 2'


